# Generated by Django 4.2.8 on 2024-05-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ucontact',
            field=models.CharField(max_length=15),
        ),
    ]
