# Generated by Django 4.2.8 on 2024-05-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_uid_user_ucaste_user_um1_user_um2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utotal',
            field=models.PositiveIntegerField(default=140),
        ),
        migrations.AddField(
            model_name='user',
            name='uyear',
            field=models.CharField(choices=[('OC', 'OC'), ('BC', 'BC'), ('MBC', 'MBC'), ('SC', 'SC'), ('ST', 'ST')], default='2005', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='um1',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='um2',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='um3',
            field=models.PositiveSmallIntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='um4',
            field=models.PositiveSmallIntegerField(default=35),
        ),
    ]
