# Generated by Django 4.2.8 on 2024-05-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_utotal_user_uyear_alter_user_um1_alter_user_um2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uyear',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2005', '2005')], default='2005', max_length=4),
        ),
    ]
