# Generated by Django 4.2.8 on 2024-05-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_uyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ucontact',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='user',
            name='uyear',
            field=models.CharField(choices=[('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006')], default='2005', max_length=4),
        ),
    ]
