# Generated by Django 4.2.8 on 2024-05-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_ucontact_user_uid_alter_user_uyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unvalue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='upass',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='urank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=30),
        ),
    ]
