# Generated by Django 4.2.8 on 2024-05-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_unvalue_user_upass_user_urank_alter_user_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
