# Generated by Django 4.2.8 on 2024-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ucutoff',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
