# Generated by Django 4.2.8 on 2024-05-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_ucutoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ucutoff',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='unvalue',
            field=models.FloatField(default=0),
        ),
    ]
