# Generated by Django 4.2.8 on 2024-05-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_user_ucutoff_alter_user_unvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ucutoff',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='unvalue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
