# Generated by Django 4.2.8 on 2024-05-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_user_uyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pref1', models.IntegerField()),
                ('pref2', models.IntegerField()),
                ('pref3', models.IntegerField()),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
