# Generated by Django 4.2.8 on 2024-05-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.AlterField(
            model_name='student',
            name='pref1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='pref2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='pref3',
            field=models.CharField(max_length=250),
        ),
    ]
