# Generated by Django 4.2.8 on 2024-05-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_student_branch_alter_student_pref1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
