# Generated by Django 4.2.8 on 2024-05-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_student_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alloted_course',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
