# Generated by Django 4.2.8 on 2024-05-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_student_alloted_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='alloted_course',
        ),
    ]
