# Generated by Django 4.2.8 on 2024-05-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_student_alloted_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allotted_course',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
