# Generated by Django 4.2.8 on 2024-05-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_student_allotted_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allotted_course',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
