# Generated by Django 4.2.8 on 2024-05-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_student_allotted_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allotted_course',
            field=models.CharField(default='Not allotted', max_length=250),
        ),
    ]
