# Generated by Django 4.2.8 on 2024-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_student_allotted_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uyear',
            field=models.PositiveIntegerField(choices=[(2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006')], default='2005'),
        ),
    ]
