# Generated by Django 4.2.8 on 2024-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_user_uyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uper',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
