# Generated by Django 4.2.8 on 2024-06-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_user_uper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uper',
        ),
    ]
